#!/usr/bin/env bash
# setup-build.sh — Full machine setup after a fresh clone (or cross-machine switch).
#
# Covers everything that is .gitignored but required to develop and test:
#   1. C++ build  (cmake + make)
#   2. r/.Renviron  (SCS_LIB_PATH / SCS_INCLUDE_PATH for R package compilation)
#   3. R package install  (R CMD INSTALL)
#   4. Python package install  (pip install ./python[dev,docs])
#   5. Git pre-push hook
#
# Usage (from repo root):
#   ./scripts/setup-build.sh          # Release build (default)
#   ./scripts/setup-build.sh Debug    # Debug build
#
# Re-running is safe: each step is idempotent.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

BUILD_TYPE="${1:-Release}"
BUILD_DIR="$ROOT/build"
CACHE="$BUILD_DIR/CMakeCache.txt"

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

step() {
  echo ""
  echo "══════════════════════════════════════════════════════════"
  printf "  %s\n" "$1"
  echo "══════════════════════════════════════════════════════════"
}

# ---------------------------------------------------------------------------
# 1. C++ build
# ---------------------------------------------------------------------------

step "1/5  C++ build"

needs_reconfigure() {
  if [[ ! -f "$CACHE" ]]; then return 0; fi
  CACHED_SOURCE=$(grep -E '^CMAKE_HOME_DIRECTORY:INTERNAL=' "$CACHE" 2>/dev/null | cut -d= -f2-)
  if [[ -z "$CACHED_SOURCE" ]]; then return 0; fi
  if [[ ! -d "$CACHED_SOURCE" ]]; then return 0; fi
  CACHED_NORM=$(cd "$CACHED_SOURCE" && pwd -P)
  ROOT_NORM=$(cd "$ROOT" && pwd -P)
  if [[ "$CACHED_NORM" != "$ROOT_NORM" ]]; then return 0; fi
  return 1
}

if needs_reconfigure; then
  if [[ -d "$BUILD_DIR" ]]; then
    echo "  Build directory was created on another machine or path — reconfiguring."
    rm -rf "$BUILD_DIR"
  fi
  cmake -B build -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
fi

cmake --build build
echo "  ✓  C++ build complete."

# ---------------------------------------------------------------------------
# 2. r/.Renviron  (SCS_LIB_PATH / SCS_INCLUDE_PATH)
# ---------------------------------------------------------------------------

step "2/5  r/.Renviron"

RENVIRON="$ROOT/r/.Renviron"
REQUIRED_LIB_PATH="$BUILD_DIR"
REQUIRED_INC_PATH="$ROOT/include"

write_renviron() {
  cat > "$RENVIRON" <<EOF
# Auto-generated by scripts/setup-build.sh — do not commit.
SCS_LIB_PATH=$REQUIRED_LIB_PATH
SCS_INCLUDE_PATH=$REQUIRED_INC_PATH
EOF
  echo "  Written: $RENVIRON"
}

if [[ ! -f "$RENVIRON" ]]; then
  echo "  r/.Renviron not found — creating."
  write_renviron
else
  # Check that the paths still point to this machine's build/include.
  CURRENT_LIB=$(grep -E '^SCS_LIB_PATH=' "$RENVIRON" 2>/dev/null | cut -d= -f2- || true)
  CURRENT_INC=$(grep -E '^SCS_INCLUDE_PATH=' "$RENVIRON" 2>/dev/null | cut -d= -f2- || true)
  if [[ "$CURRENT_LIB" != "$REQUIRED_LIB_PATH" || "$CURRENT_INC" != "$REQUIRED_INC_PATH" ]]; then
    echo "  r/.Renviron paths are stale (probably from another machine) — updating."
    write_renviron
  else
    echo "  ✓  r/.Renviron already correct."
  fi
fi

# ---------------------------------------------------------------------------
# 3. R package
# ---------------------------------------------------------------------------

step "3/5  R package install"

if command -v Rscript &>/dev/null; then
  R_LIB_USER="$(Rscript -e 'cat(.libPaths()[1])')"
  export SCS_LIB_PATH="$REQUIRED_LIB_PATH" SCS_INCLUDE_PATH="$REQUIRED_INC_PATH"
  rm -f r/src/*.o r/src/socialchoicelab.so r/src/*.dylib 2>/dev/null || true
  (cd r && R CMD INSTALL -l "$R_LIB_USER" .)
  echo "  ✓  R package installed."
else
  echo "  Rscript not found — skipping R package install."
  echo "  Install R and re-run this script before working on the R binding."
fi

# ---------------------------------------------------------------------------
# 4. Python package
# ---------------------------------------------------------------------------

step "4/5  Python package install"

if command -v pip3 &>/dev/null; then
  pip3 install --quiet "./python[dev,docs]"
  echo "  ✓  Python package installed."
elif command -v pip &>/dev/null; then
  pip install --quiet "./python[dev,docs]"
  echo "  ✓  Python package installed."
elif command -v python3 &>/dev/null; then
  python3 -m pip install --quiet "./python[dev,docs]"
  echo "  ✓  Python package installed."
else
  echo "  pip / python3 not found — skipping Python package install."
  echo "  Install Python 3 and re-run this script before working on the Python binding."
fi

# ---------------------------------------------------------------------------
# 5. Git pre-push hook
# ---------------------------------------------------------------------------

step "5/5  Git pre-push hook"

HOOK="$ROOT/.git/hooks/pre-push"
SOURCE="$ROOT/scripts/pre-push.sh"

if [[ ! -d "$ROOT/.git/hooks" ]]; then
  echo "  .git/hooks directory not found — skipping (bare clone?)."
elif [[ -f "$HOOK" ]] && diff -q "$HOOK" "$SOURCE" &>/dev/null; then
  echo "  ✓  pre-push hook already installed and up to date."
else
  cp "$SOURCE" "$HOOK"
  chmod +x "$HOOK"
  echo "  ✓  pre-push hook installed."
fi

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------

echo ""
echo "══════════════════════════════════════════════════════════"
echo "  ✓  Setup complete. Run ./scripts/check-all.sh to verify."
echo "══════════════════════════════════════════════════════════"
echo ""
